CREATE TABLE IF NOT EXISTS members (
  ID   INT(11) NOT NULL AUTO_INCREMENT,
  FIRSTNAME   VARCHAR(50) NOT NULL,
  LASTNAME    VARCHAR(50) NOT NULL,
  AGE         INT(11) NOT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=latin1;